### ISSUE TITLE
Copyright?

### ISSUE THREAD

**Issue by ghost** [ecnivtwelve/portflowio#2]
Well I'm not sure about this
![image](https://user-images.githubusercontent.com/45879791/97408643-abea0d00-18fc-11eb-8153-b2cdb820c754.png)
we don't actually own the website  
we should just put "Built with portflowio"

**Comment by ghost** [comment]
#3

**Comment by moeenio** [comment]
im not a lawyer

**Comment by ghost** [comment]
~~didn't request your review~~
