### ISSUE TITLE
Use hash instead of sha1

### ISSUE THREAD

**Issue by moeenio** [ecnivtwelve/portflowio#9]
May also imply adding a "first setup" thing

**Comment by ecnivtwelve** [comment]
first setup good idea but no hash, sha1 is more secure

**Comment by moeenio** [comment]
I'm sorry but no. Hashing, compared to sha1, can't be reversed. Also, sha1 seems like it doesn't use salts, so the generated password is always the same.

**Comment by ghost** [comment]
^
